### ISSUE TITLE
grunt isn't a dependency

### ISSUE THREAD

**Issue by dcardosods** [tactivos/grunt-htmlrefs#1]
Insert grunt into devDependencies in package.json

**Comment by johnnyhalife** [comment]
Hi @dcardosods, we have grunt as a dependency not as a dev-dependency. 

![](http://puu.sh/1y3e5)

https://github.com/tactivos/grunt-htmlrefs/blob/master/package.json#L21

Do you need anything different? Why did you raised this concern?

**Comment by dcardosods** [comment]
Isn't necessary grunt as a dependency, grunt should be in devDependencies. How it works now, when make npm install grunt-htmlrefs, grunt going to install too. In devDependencies grunt is installed only if clone the project to contribute. See https://github.com/gruntjs/grunt/pull/263, and the grunt-contrib plugins https://github.com/gruntjs/grunt-contrib. 

PS sorry for my bad english

**Comment by johnnyhalife** [comment]
got it, thanks for the feedback @dcardosods
